services:
  api1:
    image: luisbarbosagit/rinha-api-2026:latest
    container_name: rinha_api_1
    environment:
      - PORT=3000
    expose:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

  api2:
    image: luisbarbosagit/rinha-api-2026:latest
    container_name: rinha_api_2
    environment:
      - PORT=3000
    expose:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

  nginx:
    image: nginx:1.27-alpine
