services:
  api1:
    image: luisbarbosagit/rinha-api-2026:latest
    container_name: rinha_api_1
    environment:
      - PORT=3000
    expose:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

  api2:
    image: luisbarbosagit/rinha-api-2026:latest
    container_name: rinha_api_2
    environment:
      - PORT=3000
    expose:
      - "3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

  nginx:
    image: nginx:1.27-alpine
    container_name: rinha_nginx
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"
